name: 'crime_heatmap'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'crime_heatmap'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  crime_heatmap:
    +materialized: table
    example:
      +enabled: false

clean-targets:
  - "target"
  - "dbt_packages"
